### ISSUE TITLE
Media Library (all?) tag close button (x) is misplaced

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#2608]
## Description

On the media library the tag close button (x) is misplaced, and a `php artisan twill:update` didn't fix it.

<img width="391" alt="Screenshot 2024-06-13 at 09 42 24" src="https://github.com/area17/twill/assets/3182864/175ac4f8-cb9a-4fab-9818-7c5553f3581a">

This is how it looks originally (Pentagram):

<img width="298" alt="Screenshot 2024-06-13 at 09 42 40" src="https://github.com/area17/twill/assets/3182864/29b8eee2-e011-40fe-9c47-722adc9d9416">

This is how it looks on a Twill 3.1 app: 

<img width="364" alt="Screenshot 2024-06-13 at 09 48 18" src="https://github.com/area17/twill/assets/3182864/ac9992b5-93ee-487b-972e-a61a63e2a630">

### Steps to reproduce

Just go to the media library and tag any image.

Twill version:  3.3.1
Laravel version: 11
PHP version: 8.3

**Comment by Tofandel** [comment]
I can confirm

It's inheriting a `transform: translateY(-50%)` from `.a17 .vselect__field .vs__selected button`

**Comment by Tofandel** [comment]
A fix:
```css
.a17 .vselect--small.vselect--multiple .vs__selected .close, .a17 .vselect--small.vselect--multiple .vs__selected .vs__deselect {
    top: 50%;
}
```
